pool:
  vmImage: 'ubuntu-latest'
#docker run --detach --publish 5013 nginx
jobs:
  - job: Local_Scan
    steps:
      - script: docker build -t dvga . 
                docker run -t -p 5013:5013 -e WEB_HOST=0.0.0.0 dvga
        displayName: Start Nginx
      - script: >
          docker run -v $(pwd):/hawk:rw -t
          -e API_KEY="${HAWK_API_KEY}"
          stackhawk/hawkscan
        displayName: Run HawkScan
        env:
          HAWK_API_KEY: $(hawk_api_key)
