# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- master

pool:
  vmImage: ubuntu-latest


# steps:
#     # Install Checkov
#     - bash: pip3 install -r $(System.DefaultWorkingDirectory)/requirements.txt
#     - bash: python3 app.py
#       displayName: 'Install checkov'
#       name: 'install_checkov'

jobs:
  - job: Local_Scan
    steps:
    # Install Checkov
    - bash: pip3 install -r $(System.DefaultWorkingDirectory)/requirements.txt
    - bash: python3 app.py
      displayName: 'Install checkov'
      name: 'install_checkov'
    - script: >
          sleep 10
          docker run -v $(pwd):/hawk:rw -t
          -e API_KEY="${HAWK_API_KEY}"
          stackhawk/hawkscan
      displayName: Run HawkScan
      env:
          HAWK_API_KEY: $(hawk_api_key)
