
pool:
  vmImage: ubuntu-latest
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'



- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 
            chmod -R 777  ./
            docker  build -t dvga $(System.DefaultWorkingDirectory)
            docker run -t -p 5013:5013 -e WEB_HOST=0.0.0.0 dvga
            docker run -v $(pwd):/hawk:rw -t
            -e API_KEY="${HAWK_API_KEY}"
            stackhawk/hawkscan
    env:
          HAWK_API_KEY: $(hawk_api_key)
