# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- master

pool:
  vmImage: ubuntu-latest


# steps:
#     # Install Checkov
#     - bash: pip3 install -r $(System.DefaultWorkingDirectory)/requirements.txt
#     - bash: python3 app.py
#       displayName: 'Install checkov'
#       name: 'install_checkov'

jobs:
  - job: Local_Scan
    steps:
    # Install Checkov
    - bash: docker build -t dvga $(System.DefaultWorkingDirectory)
    - bash: docker run --detach --publish 8080:80 dvga
    #- bash: docker run --detach -t -p 5013:5013 -e WEB_HOST=0.0.0.0 dvga
    - bash: sleep 10
    - bash: docker ps -a
      displayName: 'Run DVGA app'
    - bash: export SERVER_PORT=8080  
    - bash: docker run -v $(pwd):/hawk:rw -t -e API_KEY="${HAWK_API_KEY}" stackhawk/hawkscan
      displayName: Run HawkScan
      env:
          HAWK_API_KEY: $(hawk_api_key)
