pool:
  vmImage: 'ubuntu-latest'
#docker run --detach --publish 5013 nginx
jobs:
  - job: Local_Scan
    steps:
      - script: docker run --detach --publish 8080 nginx
                docker pull dolevf/dvga 
                docker run --detach --publish 8080 dolevf/dvga
        displayName: Start Nginx
      - script: >
          docker run -v $(pwd):/hawk:rw -t
          -e API_KEY="${HAWK_API_KEY}"
          stackhawk/hawkscan
        displayName: Run HawkScan
        env:
          HAWK_API_KEY: $(hawk_api_key)
